import { IIngredient } from '@/lib/types';

type IngredientSeedData = Omit<IIngredient, '_id' | 'createdAt' | 'updatedAt'>;

export const ingredientSeedData: IngredientSeedData[] = [
  {
    name: 'Niacinamide',
    aliases: ['Nicotinamide', 'Vitamin B3'],
    category: 'active',
    safetyRating: 5,
    benefits: ['Reduces pore appearance', 'Controls oil production', 'Evens skin tone', 'Strengthens skin barrier'],
    concerns: [],
    bestForSkinTypes: ['oily', 'combination', 'acne-prone'],
    avoidForSkinTypes: [],
    evidenceLevel: 'strong',
    references: ['https://pubmed.ncbi.nlm.nih.gov/23927381/'],
  },
  {
    name: 'Hyaluronic Acid',
    aliases: ['Sodium Hyaluronate', 'HA'],
    category: 'active',
    safetyRating: 5,
    benefits: ['Intense hydration', 'Plumps fine lines', 'Retains moisture'],
    concerns: [],
    bestForSkinTypes: ['dry', 'normal', 'mature', 'sensitive'],
    avoidForSkinTypes: [],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Retinol',
    aliases: ['Vitamin A', 'Retinyl Palmitate'],
    category: 'active',
    safetyRating: 4,
    benefits: ['Anti-aging', 'Increases cell turnover', 'Reduces wrinkles', 'Fades dark spots'],
    concerns: ['May cause irritation', 'Increases sun sensitivity', 'Not for pregnant women'],
    bestForSkinTypes: ['normal', 'mature', 'combination'],
    avoidForSkinTypes: ['sensitive'],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Salicylic Acid',
    aliases: ['BHA', 'Beta Hydroxy Acid'],
    category: 'active',
    safetyRating: 4,
    benefits: ['Unclogs pores', 'Reduces acne', 'Exfoliates dead skin'],
    concerns: ['May cause dryness', 'Can be irritating'],
    bestForSkinTypes: ['oily', 'acne-prone', 'combination'],
    avoidForSkinTypes: ['dry', 'sensitive'],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Glycolic Acid',
    aliases: ['AHA', 'Alpha Hydroxy Acid'],
    category: 'active',
    safetyRating: 4,
    benefits: ['Exfoliates', 'Brightens skin', 'Reduces hyperpigmentation'],
    concerns: ['Increases sun sensitivity', 'May cause irritation'],
    bestForSkinTypes: ['normal', 'combination', 'mature'],
    avoidForSkinTypes: ['sensitive'],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Vitamin C',
    aliases: ['Ascorbic Acid', 'L-Ascorbic Acid', 'Sodium Ascorbyl Phosphate'],
    category: 'active',
    safetyRating: 5,
    benefits: ['Antioxidant protection', 'Brightens skin', 'Promotes collagen'],
    concerns: ['Can oxidize quickly', 'May cause tingling'],
    bestForSkinTypes: ['normal', 'combination', 'mature'],
    avoidForSkinTypes: [],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Ceramides',
    aliases: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP'],
    category: 'emollient',
    safetyRating: 5,
    benefits: ['Repairs skin barrier', 'Locks in moisture', 'Protects against irritants'],
    concerns: [],
    bestForSkinTypes: ['dry', 'sensitive', 'mature'],
    avoidForSkinTypes: [],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Squalane',
    aliases: ['Squalene'],
    category: 'emollient',
    safetyRating: 5,
    benefits: ['Lightweight hydration', 'Non-comedogenic', 'Balances oil production'],
    concerns: [],
    bestForSkinTypes: ['oily', 'combination', 'sensitive'],
    avoidForSkinTypes: [],
    evidenceLevel: 'moderate',
    references: [],
  },
  {
    name: 'Shea Butter',
    aliases: ['Butyrospermum Parkii'],
    category: 'emollient',
    safetyRating: 5,
    benefits: ['Deep moisturization', 'Soothes irritation', 'Rich in vitamins'],
    concerns: [],
    bestForSkinTypes: ['dry', 'normal'],
    avoidForSkinTypes: ['oily', 'acne-prone'],
    evidenceLevel: 'moderate',
    references: [],
  },
  {
    name: 'Glycerin',
    aliases: ['Glycerol'],
    category: 'emollient',
    safetyRating: 5,
    benefits: ['Attracts moisture', 'Softens skin', 'Non-irritating'],
    concerns: [],
    bestForSkinTypes: ['all'],
    avoidForSkinTypes: [],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Fragrance',
    aliases: ['Parfum', 'Aroma'],
    category: 'fragrance',
    safetyRating: 2,
    benefits: [],
    concerns: ['Common allergen', 'May cause irritation', 'Can trigger sensitivity'],
    bestForSkinTypes: [],
    avoidForSkinTypes: ['sensitive', 'acne-prone'],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Limonene',
    aliases: [],
    category: 'fragrance',
    safetyRating: 3,
    benefits: [],
    concerns: ['Potential allergen', 'May cause sensitivity'],
    bestForSkinTypes: [],
    avoidForSkinTypes: ['sensitive'],
    evidenceLevel: 'moderate',
    references: [],
  },
  {
    name: 'Linalool',
    aliases: [],
    category: 'fragrance',
    safetyRating: 3,
    benefits: [],
    concerns: ['Potential allergen'],
    bestForSkinTypes: [],
    avoidForSkinTypes: ['sensitive'],
    evidenceLevel: 'moderate',
    references: [],
  },
  {
    name: 'Phenoxyethanol',
    aliases: [],
    category: 'preservative',
    safetyRating: 4,
    benefits: ['Prevents bacterial growth', 'Extends product shelf life'],
    concerns: ['May cause irritation in high concentrations'],
    bestForSkinTypes: [],
    avoidForSkinTypes: [],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Parabens',
    aliases: ['Methylparaben', 'Propylparaben', 'Butylparaben'],
    category: 'preservative',
    safetyRating: 3,
    benefits: ['Effective preservation'],
    concerns: ['Controversial safety concerns', 'May cause allergic reactions'],
    bestForSkinTypes: [],
    avoidForSkinTypes: ['sensitive'],
    evidenceLevel: 'moderate',
    references: [],
  },
  {
    name: 'Sodium Lauryl Sulfate',
    aliases: ['SLS'],
    category: 'surfactant',
    safetyRating: 2,
    benefits: ['Effective cleansing', 'Creates foam'],
    concerns: ['Can strip natural oils', 'May cause irritation'],
    bestForSkinTypes: ['oily'],
    avoidForSkinTypes: ['dry', 'sensitive'],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Sodium Laureth Sulfate',
    aliases: ['SLES'],
    category: 'surfactant',
    safetyRating: 3,
    benefits: ['Gentler cleansing', 'Good foam'],
    concerns: ['May cause mild irritation'],
    bestForSkinTypes: ['normal', 'oily'],
    avoidForSkinTypes: ['sensitive'],
    evidenceLevel: 'moderate',
    references: [],
  },
  {
    name: 'Cocamidopropyl Betaine',
    aliases: [],
    category: 'surfactant',
    safetyRating: 4,
    benefits: ['Gentle cleansing', 'Mild on skin'],
    concerns: [],
    bestForSkinTypes: ['all'],
    avoidForSkinTypes: [],
    evidenceLevel: 'moderate',
    references: [],
  },
  {
    name: 'Zinc Oxide',
    aliases: [],
    category: 'active',
    safetyRating: 5,
    benefits: ['Broad-spectrum UV protection', 'Anti-inflammatory', 'Soothing'],
    concerns: ['May leave white cast'],
    bestForSkinTypes: ['sensitive', 'acne-prone'],
    avoidForSkinTypes: [],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Titanium Dioxide',
    aliases: [],
    category: 'active',
    safetyRating: 5,
    benefits: ['Physical UV protection', 'Non-irritating'],
    concerns: ['May leave white cast'],
    bestForSkinTypes: ['sensitive'],
    avoidForSkinTypes: [],
    evidenceLevel: 'strong',
    references: [],
  },
  {
    name: 'Centella Asiatica',
    aliases: ['Cica', 'Gotu Kola', 'Asiaticoside'],
    category: 'active',
    safetyRating: 5,
    benefits: ['Soothes irritation', 'Promotes healing', 'Anti-inflammatory'],
    concerns: [],
    bestForSkinTypes: ['sensitive', 'acne-prone', 'dry'],
    avoidForSkinTypes: [],
    evidenceLevel: 'moderate',
    references: [],
  },
  {
    name: 'Tea Tree Oil',
    aliases: ['Melaleuca Alternifolia'],
    category: 'active',
    safetyRating: 4,
    benefits: ['Antibacterial', 'Helps with acne', 'Natural ingredient'],
    concerns: ['Can be irritating if used undiluted'],
    bestForSkinTypes: ['oily', 'acne-prone'],
    avoidForSkinTypes: ['sensitive'],
    evidenceLevel: 'moderate',
    references: [],
  },
];
