import { ISkincareProduct } from '@/lib/types';

type ProductSeedData = Omit<ISkincareProduct, '_id' | 'createdAt' | 'updatedAt'>;

export const productSeedData: ProductSeedData[] = [
  {
    name: 'Vitamin C Serum',
    brand: 'The Ordinary',
    slug: 'the-ordinary-vitamin-c-serum',
    category: 'serum',
    imageUrl: 'https://placehold.co/600x600/1A1A1A/D4AF37?text=Vitamin+C+Serum',
    productUrl: 'https://theordinary.com',
    affiliateLinks: [],
    ingredientListRaw: 'Ascorbic Acid, Propanediol, Ethoxydiglycol, Water, Hyaluronic Acid, Phenoxyethanol',
    ingredientNames: ['Ascorbic Acid', 'Propanediol', 'Ethoxydiglycol', 'Water', 'Hyaluronic Acid', 'Phenoxyethanol'],
    skinTypes: ['normal', 'combination', 'oily'],
    price: 12.99,
    currency: 'USD',
  },
  {
    name: 'Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    slug: 'the-ordinary-niacinamide-zinc',
    category: 'serum',
    imageUrl: 'https://placehold.co/600x600/1A1A1A/D4AF37?text=Niacinamide+Serum',
    productUrl: 'https://theordinary.com',
    affiliateLinks: [],
    ingredientListRaw: 'Water, Niacinamide, Zinc PCA, Tamarindus Indica Seed Gum, Dimethyl Isosorbide, Phenoxyethanol',
    ingredientNames: ['Water', 'Niacinamide', 'Zinc PCA', 'Tamarindus Indica Seed Gum', 'Dimethyl Isosorbide', 'Phenoxyethanol'],
    skinTypes: ['oily', 'combination', 'acne-prone'],
    price: 9.99,
    currency: 'USD',
  },
  {
    name: 'Hyaluronic Acid + B5',
    brand: 'The Ordinary',
    slug: 'the-ordinary-hyaluronic-acid-b5',
    category: 'serum',
    imageUrl: 'https://placehold.co/600x600/1A1A1A/D4AF37?text=Hyaluronic+Acid',
    productUrl: 'https://theordinary.com',
    affiliateLinks: [],
    ingredientListRaw: 'Aqua, Sodium Hyaluronate, Panthenol, Ahnfeltia Concinna Extract, Glycerin, Phenoxyethanol',
    ingredientNames: ['Aqua', 'Sodium Hyaluronate', 'Panthenol', 'Ahnfeltia Concinna Extract', 'Glycerin', 'Phenoxyethanol'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    price: 11.99,
    currency: 'USD',
  },
  {
    name: 'PM Facial Moisturizing Lotion',
    brand: 'CeraVe',
    slug: 'cerave-pm-moisturizing-lotion',
    category: 'moisturizer',
    imageUrl: 'https://placehold.co/600x600/1A1A1A/D4AF37?text=CeraVe+PM',
    productUrl: 'https://cerave.com',
    affiliateLinks: [],
    ingredientListRaw: 'Water, Glycerin, Niacinamide, Ceramide NP, Ceramide AP, Ceramide EOP, Dimethicone, Phenoxyethanol',
    ingredientNames: ['Water', 'Glycerin', 'Niacinamide', 'Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Dimethicone', 'Phenoxyethanol'],
    skinTypes: ['normal', 'dry', 'sensitive'],
    price: 14.99,
    currency: 'USD',
  },
  {
    name: 'Hydrating Facial Cleanser',
    brand: 'CeraVe',
    slug: 'cerave-hydrating-cleanser',
    category: 'cleanser',
    imageUrl: 'https://placehold.co/600x600/1A1A1A/D4AF37?text=CeraVe+Cleanser',
    productUrl: 'https://cerave.com',
    affiliateLinks: [],
    ingredientListRaw: 'Water, Glycerin, Ceramide NP, Ceramide AP, Ceramide EOP, Cocamidopropyl Betaine, Phenoxyethanol',
    ingredientNames: ['Water', 'Glycerin', 'Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Cocamidopropyl Betaine', 'Phenoxyethanol'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    price: 12.99,
    currency: 'USD',
  },
  {
    name: 'Ultra Repair Cream',
    brand: 'First Aid Beauty',
    slug: 'fab-ultra-repair-cream',
    category: 'moisturizer',
    imageUrl: 'https://placehold.co/600x600/1A1A1A/D4AF37?text=FAB+Cream',
    productUrl: 'https://firstaidbeauty.com',
    affiliateLinks: [],
    ingredientListRaw: 'Water, Glycerin, Shea Butter, Squalane, Dimethicone, Ceramides, Centella Asiatica, Phenoxyethanol',
    ingredientNames: ['Water', 'Glycerin', 'Shea Butter', 'Squalane', 'Dimethicone', 'Ceramides', 'Centella Asiatica', 'Phenoxyethanol'],
    skinTypes: ['dry', 'sensitive', 'normal'],
    price: 38.00,
    currency: 'USD',
  },
  {
    name: 'Unseen Sunscreen SPF 40',
    brand: 'Supergoop',
    slug: 'supergoop-unseen-sunscreen',
    category: 'sunscreen',
    imageUrl: 'https://placehold.co/600x600/1A1A1A/D4AF37?text=Supergoop+SPF',
    productUrl: 'https://supergoop.com',
    affiliateLinks: [],
    ingredientListRaw: 'Dimethicone, Avobenzone, Homosalate, Octisalate, Octocrylene, Squalane, Vitamin C',
    ingredientNames: ['Dimethicone', 'Avobenzone', 'Homosalate', 'Octisalate', 'Octocrylene', 'Squalane', 'Vitamin C'],
    skinTypes: ['all', 'oily', 'combination'],
    price: 38.00,
    currency: 'USD',
  },
  {
    name: 'BHA Exfoliant',
    brand: 'Paula\'s Choice',
    slug: 'paulas-choice-bha-exfoliant',
    category: 'treatment',
    imageUrl: 'https://placehold.co/600x600/1A1A1A/D4AF37?text=PC+BHA',
    productUrl: 'https://paulaschoice.com',
    affiliateLinks: [],
    ingredientListRaw: 'Water, Salicylic Acid, Butylene Glycol, Methylpropanediol, Green Tea Extract, Phenoxyethanol',
    ingredientNames: ['Water', 'Salicylic Acid', 'Butylene Glycol', 'Methylpropanediol', 'Green Tea Extract', 'Phenoxyethanol'],
    skinTypes: ['oily', 'combination', 'acne-prone'],
    price: 32.00,
    currency: 'USD',
  },
];
