import { ITopic } from '@/lib/types';

type TopicSeedData = Omit<ITopic, '_id' | 'createdAt' | 'updatedAt' | 'relatedProductIds'>;

export const topicSeedData: TopicSeedData[] = [
  {
    title: 'The Complete Guide to Niacinamide for Oily Skin',
    slug: 'complete-guide-niacinamide-oily-skin',
    primaryKeyword: 'niacinamide for oily skin',
    secondaryKeywords: ['niacinamide serum', 'oil control', 'pore minimizer', 'sebum regulation'],
    ideaType: 'evergreen',
    source: 'manual',
    trendScore: 85,
    monetizationScore: 90,
    difficultyScore: 35,
    status: 'new',
  },
  {
    title: 'Hyaluronic Acid vs Glycerin: Which Hydrator is Right for You?',
    slug: 'hyaluronic-acid-vs-glycerin-hydration',
    primaryKeyword: 'hyaluronic acid vs glycerin',
    secondaryKeywords: ['hydration', 'humectants', 'dry skin', 'moisture retention'],
    ideaType: 'evergreen',
    source: 'manual',
    trendScore: 78,
    monetizationScore: 82,
    difficultyScore: 40,
    status: 'new',
  },
  {
    title: 'Best Vitamin C Serums Under $30 in 2024',
    slug: 'best-vitamin-c-serums-under-30-2024',
    primaryKeyword: 'best vitamin c serum',
    secondaryKeywords: ['affordable skincare', 'vitamin c benefits', 'brightening serum', 'antioxidant'],
    ideaType: 'trend',
    source: 'google_trends',
    trendScore: 92,
    monetizationScore: 95,
    difficultyScore: 50,
    status: 'new',
  },
  {
    title: 'How to Build a Minimalist Skincare Routine',
    slug: 'minimalist-skincare-routine-guide',
    primaryKeyword: 'minimalist skincare routine',
    secondaryKeywords: ['simple skincare', 'skincare basics', 'beginner routine', 'essential products'],
    ideaType: 'evergreen',
    source: 'reddit',
    trendScore: 75,
    monetizationScore: 70,
    difficultyScore: 30,
    status: 'new',
  },
  {
    title: 'Retinol 101: Everything Beginners Need to Know',
    slug: 'retinol-beginners-guide-101',
    primaryKeyword: 'retinol for beginners',
    secondaryKeywords: ['anti-aging', 'retinol side effects', 'how to use retinol', 'vitamin a skincare'],
    ideaType: 'evergreen',
    source: 'manual',
    trendScore: 88,
    monetizationScore: 85,
    difficultyScore: 45,
    status: 'new',
  },
];
